export enum Genres {
  social = 'Social',
  foodAndDining = 'Food and Dining',
  restaurants = 'Restaurants',
  american = 'American',
  seafood = 'Seafood',
  steakhouses = 'Steakhouses',
  french = 'French',
  international = 'International',
  italian = 'Italian',
  cafes = 'Cafes',
  coffeeAndTeaHouses = 'Coffee and Tea Houses',
  bars = 'Bars',
  entertainment = 'Entertainment',
  musicAndShowVenues = 'Music and Show Venues',
  japanese = 'Japanese',
  sushi = 'Sushi',
  bakeries = 'Bakeries',
}
